import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const submit = () => {
    alert("fom")
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <div className={styles.form}>
          <div className={styles.inputContainer}>
            <label className={styles.label} for="email">Email</label>
            <input className={styles.input} type="email" id="email" name="email" />
          </div>
          <div className={styles.inputContainer}>
            <label className={styles.label} for="password">Senha</label>
            <input className={styles.input} v type="password" id="password" name="password" />
          </div>
          <div className={styles.inputContainer}>
            <label className={styles.label} for="confirmPassword">Repita a Senha</label>
            <input className={styles.input} type="confirmPassword" id="confirmPassword" name="confirmPassword" />
          </div>
          <div className={styles.inputContainer}>
            <button className={styles.button} onClick={submit}>Cadastrar</button>
          </div>
        </div>
      </div>
    </>
  )
}
